# Generated by Django 5.2.6 on 2025-09-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
