# Generated by Django 5.2.6 on 2025-10-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_app", "0002_note_user_tag_user_alter_tag_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="is_todo",
            field=models.BooleanField(default=False),
        ),
    ]
