# Generated by Django 5.2.6 on 2025-10-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes_app", "0003_note_deadline_note_is_expired_note_is_todo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="is_expired",
        ),
    ]
